# Konfiguracja GitHub Pages
# Dodaje ścieżki, które normalnie byłyby ignorowane (zaczynające się od kropki)
include:
  - .well-known
  - .txt  # Dodajemy, aby uwzględnić pliki .txt w ukrytych folderach
